name: Deploy Metabase to Cloud Run

on:
  push:
    branches:
      - main


env:
  PROJECT_ID: swift-implement-405417
  REGION: us-central1
  SERVICE: metabase
  IMAGE: metabase/metabase:latest  # Change to your own if using Dockerfile

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image=${{ env.IMAGE }} \
            --platform=managed \
            --region=${{ env.REGION }} \
            --allow-unauthenticated \
            --port=3000 \
            --timeout=600s \
            --memory=1Gi \
            --set-env-vars PORT=8080
        



            
